//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBPresenceLight.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppNavigation
    {

        public AppNavigation()
        {
            this.AppNavigationPermissions = new HashSet<AppNavigationPermission>();
        }
    
        public int AppNavigationId { get; set; }
        public string NavigationLabel { get; set; }
        public int NavigationLevel { get; set; }
        public int NavigationOrder { get; set; }
    
        public virtual ICollection<AppNavigationPermission> AppNavigationPermissions { get; set; }
    }
}
